### ISSUE TITLE
Project To Do

### ISSUE THREAD

**Issue by ColinLefter** [ubco-W2022T2-data301/project-group-group15#2]
## **Phase 1: Data Loading**
**Assigned to Colin**:
- [x] Write Python code guidelines for project

**Assigned to Keisha:**
- [ ] To be determined

**Assigned to Yigit:**
- [ ] To be determined

**Assigned to All:**
- [x] Write code of conduct README file (still need to approve of content as a group)
- [x] Write project vision statement (still need to approve of content as a group)

**Task list:**
- [x] Identify all relevant variables for our analysis from each data set
- [x] Delete irrelevant columns from each data set (via Microsoft Excel) and submit a pull request on GitHub to upload all of the data files to the processed data folder
- [ ] Discuss pull request as a group and finalize processed data set (accept pull request on GitHub)
- [x] Identify parameters for the central algorithm (e.g. holding period, preferred industries, capital invested)
- [x] Create general class framework in Jupyter Notebook and import relevant libraries (Plotly, Pandas, Numpy, Scikit-Learn, Seaborn)
- [x] Load data into Pandas data frames and develop any helper functions used in data wrangling, processing and cleaning

---

## **Phase 2: Analysis**
**Assigned to Colin**:
- [ ] To be determined

**Assigned to Keisha:**
- [ ] To be determined

**Assigned to Yigit:**
- [ ] To be determined

**Assigned to All:**
- [x] Identify analysis algorithms to be used and developed (concepts, use and method of construction)
- [ ] Identify how each algorithm may build upon each other
- [ ] Identify points where data visualization takes place (e.g. within all analysis algorithms, include a case where the relevant data is plotted on command)

**Task list:**
- [ ] Write analysis algorithms into Jupyter Notebook documents (specific algorithms will be assigned to different group members at a later stage)
- [ ] Write data visualization components into analysis algorithms / create separate functions for doing so (specific plots will be assigned to different group members at a later stage)
